### ISSUE TITLE
AttributeError: 'module' object has no attribute 'arange'

### ISSUE THREAD

**Issue by brotherNanNan** [fxia22/kdnet.pytorch#2]
Hi,

Thank you for releasing the code. I am now trying to run your code . But i encounter a mistake. Here is the error.

{'Earphone': 0, 'Motorbike': 1, 'Rocket': 2, 'Car': 3, 'Laptop': 4, 'Cap': 5, 'Skateboard': 6, 'Lamp': 10, 'Guitar': 8, 'Bag': 9, 'Mug': 7, 'Table': 11, 'Airplane': 12, 'Pistol': 13, 'Chair': 14, 'Knife': 15}
(16, 15990)
Traceback (most recent call last):
  File "train.py", line 153, in <module>
    pred = net(points_v, cutdim_v)
  File "/home/nnqin/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 41, in forward
    x1 = kdconv(x, 2048, 8, c[-1], self.conv1)
  File "train.py", line 33, in kdconv
    sel = Variable(sel + (torch.arange(0,dim) * 3).long())
AttributeError: 'module' object has no attribute 'arange'

Seems like i am using the wrong version of pytorch? Any idea? Thank you for helping me!

Bests,
nnqin

**Comment by fxia22** [comment]
This implementation uses `torch=0.1.12.post2`

**Comment by brotherNanNan** [comment]
thanks for your reply, it works now~
