### ISSUE TITLE
Running train.py

### ISSUE THREAD

**Issue by btgraham** [fxia22/kdnet.pytorch#3]
Hello. Running 'python train.py' with PyTorch version '0.2.0+490d5c2' gives me an error:
`
{'Airplane': 0, 'Bag': 1, 'Cap': 2, 'Car': 3, 'Chair': 4, 'Earphone': 5, 'Guitar': 6, 'Knife': 7, 'Lamp': 8, 'Laptop': 9, 'Motorbike': 10, 'Mug': 11, 'Pistol': 12, 'Rocket': 13, 'Skateboard': 14, 'Table': 15}
16 15990
Traceback (most recent call last):
  File "train.py", line 129, in <module>
    left_ps, right_ps, dim = split_ps(item)
  File "train.py", line 60, in split_ps
    dim = torch.max(diff, dim = 1)[1][0,0]

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)
`

**Comment by jyothishkjames** [comment]
Hello,

I am getting the same error.

Thanks

**Comment by fxia22** [comment]
Looks like pytorch changed max function, I will address this soon.
