### ISSUE TITLE
"shapenetcore_partanno_segmentation_benchmark_v0 " where to find complete dataset

### ISSUE THREAD

**Issue by saira05** [fxia22/kdnet.pytorch#6]
hi,
i am unable to download this complete dataset. i downloaded it from "https://1drv.ms/u/s!ApbTjxa06z9CgQnl-Qm6KI3Ywbe1" but there are some folders  that were missing in it like points and point_labels. and that folders are used in code so i am stuck at this point can you plz help me 
 thanx

**Comment by fxia22** [comment]
can you download it from here: https://shapenet.cs.stanford.edu/ericyi/shapenetcore_partanno_segmentation_benchmark_v0.zip ?

**Comment by saira05** [comment]
thankyou so much :)

**Comment by jstmn** [comment]
Hi, this was from a while ago but where can I download this data from?
